name: chacicd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.4'

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release
      