name: chalotte
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # UI
  # html: ^0.15.0
  bottom_navy_bar: ^6.0.0
  snapping_sheet: ^3.1.0
  cached_network_image: ^3.3.1
  go_router: ^13.1.0
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  flutter_staggered_grid_view: ^0.7.0

  # Dart data class
  json_annotation: ^4.8.0
  freezed: ^2.3.2

  # Info package
  package_info_plus: ^3.0.3
  device_info: ^2.0.3

  # Network
  connectivity_plus: ^3.0.3

  # Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Value equality
  equatable: ^2.0.5

  # State management
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  # Remote API
  dio: ^5.0.0

  # Dependency Injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  # Permission app
  # permission_handler: ^10.0.0

  # Logger
  pretty_dio_logger: ^1.3.1

  # Native Splash
  flutter_native_splash: ^2.2.16

  # Languages
  intl_utils: ^2.8.6

  # Firebase
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # Dart data class
  json_serializable: ^6.6.1

  # Code generators
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4

  # Gen assets
  flutter_gen_runner:

flutter_gen:
  output: lib/src/gen/
  integrations:
    flutter_svg: true
    flare_flutter: false
  assets:
    outputs:
      style: camel-case

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: SF-Pro-Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf

flutter_intl:
  enabled: true
  arb_dir: lib/src/app_language/l10n
  output_dir: lib/src/app_language/generated
